USB_VID = 0x6666
USB_PID = 0xFED2
USB_PRODUCT = "KeyPedal"
USB_MANUFACTURER = "fasteddy516"
USB_INTERFACE_NAME = "KeyPedal"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"
