USB_VID = 0x6666
USB_PID = 0xFED1
USB_PRODUCT = "KeyLight Controller"
USB_MANUFACTURER = "fasteddy516"
USB_INTERFACE_NAME = "KeyLight Controller"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"
