USB_VID = 0x6666
USB_PID = 0xFED0
USB_PRODUCT = "KeyLight"
USB_MANUFACTURER = "fasteddy516"
USB_INTERFACE_NAME = "KeyLight"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_PICODVI = 1
